CREATE TABLE IF NOT EXISTS work_report_settings (
 id INT NOT NULL PRIMARY KEY,
 version INT NOT NULL DEFAULT 0,
 rules JSON NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
